common: &common
  adapter: postgresql
  username: postgres
  password:
  port: 5433
  encoding: unicode
  pool: 5
  timeout: 5000

local: &local
  host: localhost

# -----------------
# *** part ***
# -----------------

development:
  <<: *common
  <<: *local
  database: part_production

production:
  <<: *common
  <<: *local
  database: part_production


test:
  <<: *common
  <<: *local
  database: part_test

